name: Release

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Version packages PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tsdoc-pr:
    name: Generated TSDoc PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Install docs-util Dependencies
        run: yarn
        working-directory: docs-util

      - name: Build packages
        run: yarn build
        working-directory: docs-util

      - name: Run docblock generator
        run: "yarn start run:commit ${{ github.sha	}}"
        working-directory: docs-util/packages/docblock-generator

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Generated TSDocs"
          body: "This PR holds all generated TSDocs for the upcoming release."
          branch: "chore/generate-tsdocs"
          team-reviewers: "@medusajs/docs"
          add-paths: packages/**